team-joytas/wooco-fe

.github/workflows/pr_webhook.yml

디스코드 웹훅 설정 커스텀
github 기본 웹훅을 사용하면 디스코드 멘션 기능을 사용할 수 없어 github actions로 커스텀한 것으로 변경합니다
- ✨ Github Actions 디스코드 PR 웹훅 추가
- UI 변경 사항이 있는 경우 스크린샷을 포함합니다.
- 리뷰어가 알 필요가 있는 추가 정보나 문서, 참고 링크를 포함합니다.

[기능] PR 웹훅 스크립트 추가

---

.github/workflows/pr_webhook.yml

- 깃헙 액션에서 시크릿 변수에 접근할 수 없어 발생하고 있는 오류 수정
- ✨ 트리거 동작 방법을 `pull_request` 에서 `pull_request_target` 으로 변경
-

[수정] 깃헙 액션이 시크릿 변수에 접근할 수 있도록 변경

---

src/app/(legal)/privacy/page.tsx
src/app/(legal)/terms/page.tsx
src/app/components/Header.tsx

- 서비스 약관, 개인정보 처리 방침 페이지 구현
- ✨ 페이지 UI 구현
- ✨ 헤더 로고 이미지 내비게이션 추가
|이용약관|개인정보|
|---|---|
|![](https://github.com/user-attachments/assets/7707d6f0-b72e-4b11-a4cd-b2a9be0e0f29)|![](https://github.com/user-attachments/assets/050c4ffa-4148-4f9e-8b26-fccd0259d769)|

[기능] 약관/방침 페이지 구현

---

src/app/components/KakaoMap.tsx
src/app/schedules/[id]/update/page.tsx
src/app/schedules/components/CourseCard.tsx
src/app/schedules/getData.ts
src/app/schedules/new/page.tsx
src/app/schedules/page.tsx

- 코스 플랜 목록 페이지 구현
- ✨ 카카오맵 api 연동
- ✨ 코스 플랜 컴포넌트 생성
- ✨ 주소 클립보드 복사 기능
https://github.com/user-attachments/assets/9618ba30-8575-4f2a-977f-d0f787de789c
- 영상 찍을땐 포인터로 안바뀌는데 코드에는 포인터 다 적용되어 있음
- .env 추가 설정 필요!!!

[기능] 나의 코스 플랜 페이지 구현

---

src/app/components/Menu.tsx
src/app/users/[id]/page.tsx
src/app/users/[id]/setting/page.tsx
src/app/users/setting/page.tsx

- 프로필 수정 페이지 UI 구현
- ✨ 페이지 UI 구현
- ✨ 유효성 검사 로직
https://github.com/user-attachments/assets/c9a6d2ab-12a9-4cd3-a204-edba352802ee
- 이것두 이전 PR 머지되면 rebase 해서 다시 올릴게여
- 오늘 이제 새로 못올릴 것 같아서 미리 다 올려둡니닷.. 천천히 봐주셔도 됩니다..

[기능] 프로필 수정 페이지 구현

---

src/app/components/(layout)/Header.tsx
src/app/components/RegionCascader.tsx
src/app/courses/add-region/page.tsx
src/app/courses/page.tsx
src/app/layout.tsx

- 관심 지역 추가 페이지 구현에 대한 PR
- ✨ 관심 지역 추가 페이지 UI 구현
- ✨ 지역 검색 Cascader 컴포넌트 생성
- ✨ Ant design 디자인 커스텀을 위한 `<ConfigProvider />` 사용
https://github.com/user-attachments/assets/2807fd2b-cade-4fa2-b527-c9000c7e452d
- 지역 선택 후 어떤 이벤트가 있어야 할지 고민돼서,,, 우선 목록 페이지로 내비게이션되게끔 구현했습니당
- 단순히 지역 선택 Cascader 하나만 있는데, 굳이 페이지로 나눠야하나 싶기도 합니다
- 의견 나누면 좋을 것 같아용

[기능] 관심 지역 추가 페이지 구현 및 지역 검색 컴포넌트 생성

---

app/courses/page.tsx
app/layout.tsx
src/features/course/card-grid-course.tsx
src/features/course/card-list-course.tsx
src/shared/ui/SelectCategories.tsx
src/views/list-course/index.tsx
src/widgets/course-list/index.tsx
src/widgets/default-header/index.tsx
src/widgets/header/index.tsx
src/widgets/list-course/index.tsx

- 코스 목록 페이지 구현 PR
- ✨ 리스트뷰 구현
- ✨그리드뷰 구현
|리스트뷰|그리드뷰|
|---|---|
|![](https://github.com/user-attachments/assets/a84cd67c-0ff0-4ab8-be58-7ebbdcefb8c9)|![](https://github.com/user-attachments/assets/547020ae-b3ed-4c28-ac19-945c42c89784)|
- 메인페이지에서 쓰는 그리드뷰 카드랑 스타일이 조금 달라야해서 새로 파일 만들긴 했는데, 나중에 컴포넌트 하나로 통합해서 사용하는걸로 수정할게용

[기능] 코스 목록 페이지 구현

---

src/entities/course/api.ts
src/entities/course/query.ts
src/shared/ui/SelectCategories.tsx
src/views/list-course/index.tsx

- 코스 목록의 카테고리 설정 기능 추가를 위한 PR
- ✨ 카테고리 설정 개수 1개로 제한
- ✨ 카테고리 포함 api 요청
https://github.com/user-attachments/assets/06921f16-01d1-4210-bfcb-51118e0447a6
- [카테고리 개수 대화 스레드](https://discord.com/channels/1310419383830577213/1310420264454066187/1333092890536050710)

[기능] 카테고리 설정 기능 추가

---

src/entities/plan/api.ts
src/entities/plan/query.ts
src/widgets/course-plan-detail-layout/index.tsx
src/widgets/course-plan-form-layout/index.tsx
src/widgets/header/index.tsx

- 플랜 삭제 및 코스로 공유 기능 구현을 위한 PR
- ✨ 플랜 삭제 api 연결
- ✨ 플랜 공유/수정/삭제 모달 수정
- ✨ 플랜-코스로 공유 기능 구현
https://github.com/user-attachments/assets/8c0a29d2-d257-4420-879f-75d4c74bf9a9
- 코스로 공유할 때 세션스토리지에 한 이유는 영구 저장까지는 할 필요 없을 것 같아서 세션으로 했습니다
- 코스 생성 페이지에서 이탈 시(뒤로가기, 생성 완료 후 페이지 이동 등등) 세션스토리지 비우게 했어요

[기능 및 수정] 플랜 삭제 api 연결 및 플랜-코스로 공유 기능 구현

---

app/users/[id]/wishlist/page.tsx
src/entities/course/query.ts
src/features/main/section-like-course.tsx
src/shared/ui/NoLikedCourse.tsx
src/shared/ui/RegionCascader.tsx
src/shared/ui/SelectCategories.tsx
src/views/list-course/index.tsx
src/views/list-like-course/index.tsx
src/views/main-course/index.tsx
src/widgets/course-list-layout/index.tsx

- 이 PR은 유저 위시리스트 로직 수정 및 컴포넌트 분리를 위한 PR입니다.
- ✨ 유저 위시리스트 로직 수정
- ✨ 유저 위시리스트 컴포넌트 분리
- ✨ ui 이상함 수정
- 위시리스트 쿼리가 본인의 위시리스트를 보여주는 쿼리로 작성되어 있음
- 로직 수정: path에 위치해있는 유저의 위시리스트를 보여주는 것으로 변경
- padding 없는 부분, ui 이상한 부분 수정
- listcourse 에서 컴포넌트 분리 -> 복잡도 개선

[수정] 유저 위시리스트 로직 수정 및 컴포넌트 분리

---

src/entities/user/query.ts
src/shared/store/regionStore.ts
src/shared/ui/RegionCascader.tsx
src/views/list-course/index.tsx
src/views/main-course/index.tsx

- 관심 지역 목록 관련 기능 수정을 위한 PR
- ✨ 관심 지역 목록 캐싱 활용을 위한 useRegionStore 수정
- ✨ 관심 지역 선택 Cascader에서 관심 지역 없을 경우, 선택 불가

[수정] 관심 지역 목록 관련 오류 수정 및 리팩토링

---

src/features/course/form-course.tsx
src/widgets/course-plan-detail-layout/index.tsx
src/widgets/course-plan-form-layout/index.tsx

- 플랜을 코스로 공유하는 기능의 연동 정보 수정을 위한 PR
- ✨ 세션 스토리지에 지역, 장소, 방문 일자 정보만 저장
- ✨ 지역 재선택 시 장소 목록 초기화
https://github.com/user-attachments/assets/553db416-df14-48d6-9a23-9d171c5413dc

[수정] 플랜-코스로 공유 기능의 연동 정보 수정

---

app/globals.css
src/features/plan/blank-tooltip.tsx
src/views/list-plan/index.tsx
src/widgets/floating-write-btn/index.tsx

- ✨ tooltip component 탈 antd
- ✨ floating button의 isClick 함수를 lifting해 상태 전달
- #124 
- 기존
- 기획
- 수정

[기능 및 수정] 플랜 목록이 비어있는 경우, 안내 문구와 플로팅 버튼의 겹침 해결

---

src/widgets/floating-write-btn/index.tsx

- 플로팅 버튼의 클릭 안되는 문제를 해결하기 위한 PR
- ✨ 버튼 컴포넌트 내부에서도 클릭 여부 관리
- closes #141

[수정] 코스/플랜 생성 버튼 에러 해결

---

src/shared/ui/NoLikedCourse.tsx

-  ✨텍스트 메시지 변경
-  유저의 -> 아직
- #131 
- 이슈에서 명시한 "나의"보다 "아직"문구가 더 적합한 것 같아 이렇게 수정했습니다.

 [수정-관심 목록] 알림 문구 명칭 변경

---

app/oauth/[provider]/callback/page.tsx
app/oauth/kakao/callback/page.tsx
src/entities/auth/api/get-login-url.ts
src/entities/auth/api/post-login.ts

- OAuth 관련 엔드포인트 변경 사항 반영
- ✨ `/api/v1/oauth2/authorization/kakao`
- Redirect 목표 origin이 kakao 인증 서버인 관계로, CORS 이슈를 해결하고자 Axios 요청이 아닌 주소 값 String 사용 
- ✨`/api/v1/oauth2/kakao/login`
- callback uri로부터 query params "code", "state"를 받아 BE로 전달
- ✨ 확장성을 고려해 callback uri의 "kakao"에 해당하는 provider 값을 path variable로 지정
- closes #209 
https://devtalk.kakao.com/t/cors-error/121958/3

feat: 인증관련 엔드 포인트 수정

---

firbase.ts
src/entities/place/api/get-place-reviews.ts
src/features/header-elements/title-with-tag-style.tsx
src/views/detail-comment/index.tsx
src/views/detail-place/index.tsx
src/views/list-place-review/index.tsx
src/widgets/default-footer/index.tsx
src/widgets/header/action-header.tsx
src/widgets/review-comment-card/index.tsx

- 장소 상세 페이지 관련 기능 추가 및 코드 수정을 위한 PR입니다.
- ✨ 장소 상세 페이지의 제목 위치 수정
- ✨ 장소 리뷰 카드 디자인 반영
- ✨ 작성하기 버튼의 태그를 button으로 수정
- ✨ 장소 상세 페이지의 레이아웃 전반적으로 수정
- ✨ 리뷰 태그 정보 없을 경우 그래프 나타나지 않도록 설정
- ✨ 리뷰 조회 API의 gcTime을 0으로 설정하여, 리뷰 작성 후 뒤로가기 시에도 정상적으로 조회되도록 수정
- ✨ 잘못된 정보 제보를 위한 푸터 추가
- ✨ 장소 페이지에도 푸터 표시되도록 설정 (디자인 반영)
- closes #234 , #235 , #236 
|항목|원본|수정된 버전|
|---|---|---|
|리뷰 카드|![](https://github.com/user-attachments/assets/27c1e7f8-49d6-45e2-ae5b-ecf23213e3c2)|![](https://github.com/user-attachments/assets/df33d9b9-a9a6-4831-b03c-e4b86f8352a5)|
|그래프|![](https://github.com/user-attachments/assets/4b6411f0-f4df-4966-ba58-3df2b6458799)|![](https://github.com/user-attachments/assets/63ff0a8e-d118-49bc-9e30-cec80a0e6eeb)|
|전체 페이지|![](https://github.com/user-attachments/assets/4a722f4c-4284-4500-9722-fcc3a824f …

[기능 및 수정] 장소 상세 페이지의 디자인 반영 및 기능 수정

---

src/entities/course/api/get-course.ts
src/entities/plan/api/get-plan.ts
src/widgets/course-plan-detail-layout/detail-layout.tsx
src/widgets/course-plan-form-layout/index.tsx

- #241  버그 픽스
- ✨ 더 이상 플랜을 코스로 만들 때, 날짜 정보가 넘어가지 않습니다.
- ✨ 이제 플랜을 코스로 만들 때, 제목과 설명이 자동으로 이전됩니다.
- ✨ 플랜과 코스에서 공통으로 사용하는 컴포넌트에서 불필요한 네트워크 요청이 발생하던 현상을 수정했습니다.
- closes #241

[플랜 공유] 플랜을 코스로 변환하는 과정에서 미래 날짜 데이터가 그대로 넘어오는 현상 수정

---

src/features/header-elements/title-with-tag-style.tsx
src/widgets/header/course-plan-header.tsx

- 코스 상세, 플랜 상세, 장소 상세 페이지에 사용되는 TitleWithTagStyle 컴포넌트를 리팩토링했습니다.
- 스켈레톤 공통 처리 목적
- ✨ title 길이 삼항연산 위치 이동
-
-
-

[리팩토링] TitleWithTagStyle 컴포넌트 리팩토링

---

src/features/header-elements/title-with-tag-style.tsx

- title 길이에 따라 달라져야 하는 렌더링 값을 반대로 설정한 부분 수정

[수정/긴급] TitleWithTagStyle의 title 길이 연산자 수정

---

app/layout.tsx
src/features/course-card/grid-card/grid-card.tsx
src/features/course-card/list-card/list-card.tsx
src/features/modal/index.ts
src/features/modal/share-modal.tsx
src/features/place-collapse/place-collapse.tsx
src/features/place/form-review.tsx
src/shared/lib/MessageProvider.tsx
src/shared/lib/index.ts
src/views/detail-place/index.tsx
src/views/detail-plan/index.tsx
src/widgets/course-plan-detail-layout/detail-layout.tsx
src/widgets/course-plan-form-layout/index.tsx

- 플랜을 코스로 공유하기 위한 모달 추가
- 토스트 메세지용 컨텍스트를 설정하기 위한 Provider 컴포넌트 생성
- ✨ MessageProvider 컴포넌트 생성
- `contextHolder`는 Provider 컴포넌트 내부에서 렌더링하고, `messageApi`는 Context로 공유하여, 모든 컴포넌트에서 토스트 메시지를 사용할 수 있도록 구조를 개선했습니다.
- ✨ CourseModal -> ShareModal 변경하여 모달 재사용
- ✨ 플랜 상세 조회 페이지의 얼리 리턴 순서 변경 
- isLoading을 가장 먼저 처리하도록, `!plan` 조건은 isError와 동일하게 처리하도록 수정
- closes #173 
https://github.com/user-attachments/assets/763b5a9f-8609-4152-bb8d-78d9ab247445
-

[기능] 플랜을 코스로 공유하는 모달 추가 및 토스트 메세지용 컨텍스트 생성

---

src/features/course-card/action-bar/ui/course-action-bar.tsx
src/features/header-elements/title-with-tag-style.tsx
src/features/user/user-profile-section.tsx
src/widgets/header/action-header.tsx
src/widgets/header/course-plan-header.tsx

- #244  해결
- ✨ 마이 페이지, 장소 상세 페이지의 Header에 sticky postion을 부여
- ✨ toggle tab의 고정 위치 수정
- 코드가 수정된 페이지에 포함된 외부 호출 icon을 자체 아이콘으로 수정
- closes #244

[수정-마이페이지] 탭 고정 위치 수정

---

src/entities/course/api/delete-course.ts
src/entities/course/api/post-course.ts
src/entities/place/api/get-place.ts
src/entities/place/model/type.ts
src/entities/plan/api/post-plan.ts
src/entities/user/api/get-user-courses.ts
src/views/detail-place/index.tsx
src/widgets/header/course-plan-header.tsx

- 리액트 쿼리 캐싱 설정을 수정하고, 서버 응답의 데이터타입을 설정했습니다.
- ✨ 코스, 플랜, 댓글 삭제/수저: `refetchQueries` (-> 즉시 목록 업데이트)
- ✨ 코스, 플랜, 댓글 추가: `invalidateQueries`
- ✨ predicate: 쿼리키의 부분 일치로 invalidate하는 옵션
- `queryClient.refetchQueries({ predicate: (query) => query.queryKey[0] === 'courses'})`
: 쿼리키가 'courses'로 시작하는 모든 쿼리의 캐시 무효화
- ✨ id라는 변수가 이외의 코드에서 대부분 string으로 사용되어, 데이터타입을 수정했습니다.
-
- UI 변경 사항이 있는 경우 스크린샷을 포함합니다.
|함수 | 설명 | 서버 요청 발생 시점|
|-- | -- | --|
|invalidateQueries | 쿼리를 무효화해서 다음 render 또는 focus 시 refetch되게 만듦 | ❌ 즉시 X, 조건 충족 시|
|refetchQueries | 쿼리를 즉시 서버로부터 재요청함 | ✅ 바로 발생|

[수정] 리액트 쿼리 캐싱 관련 설정 수정 및 데이터타입 설정

---

src/features/comment-card/comment-card.tsx
src/views/detail-course/index.tsx
src/views/list-comment/index.tsx

- 코스 상세 페이지의 댓글 목록에서는 수정/삭제가 불가능하도록 했습니다. (지난 회의에서 논의)
- ✨ `showKebab` props 추가
- closes #263 
-
- #275 PR에 의존성을 가지고 있는 변경사항이라, 빌드 테스트는 해당 PR 머지 이후에 해보겠습니다!

[수정] 코스 상세 페이지에서 댓글 KebabMenu 아이콘 미표시

---

src/features/floating-write-btn/floating-write-btn.tsx

- 자식 요소의 z-index가 올바르게 적용될 수 있도록 부모 div에서 z-index 속성을 제거했습니다.
- 이로 인해 `FloatingWriteButton`의 background가 의도대로 header와 같은 [쌓임 맥락](https://developer.mozilla.org/ko/docs/Web/CSS/CSS_positioned_layout/Stacking_context)을 가집니다.
- resolves #274

[수정-코스,플랜 목록] 플로팅 버튼의 z-index 조정

---

src/features/comment-card/comment-card.tsx
src/features/course-form/elements/contents.tsx
src/features/course-form/elements/title.tsx
src/features/place/form-review.tsx
src/views/list-comment/index.tsx
src/views/onboard/index.tsx
src/views/search-place/index.tsx
src/views/update-user/index.tsx

- iOS 모바일에서 입력 시도 시 화면이 확대되는 문제를 해결했습니다.
- 세부적인 디자인을 수정했습니다.
- ✨ input, textarea의 text 크기 및 전체적인 비율 조정
- 타겟 텍스트 크기가 11px 이라면, 16px로 설정해둔 후 `scale=0.6875` 설정 (11/16=0.6875)
- width, height 등등도 같은 비율로 조정
- ✨ 온보딩 페이지의 디자인을 반영하기 위해 '시작하기' 버튼을 추가했습니다.
- ✨ 리뷰 작성 영역을 참고하여 코스 작성 페이지의 상세 설명 영역에도 `handleResize` 적용
closes #116 
- 모바일 로컬 서버로는 로그인된 상태로 테스트해볼 수가 없어서 (로컬 서버가 dev 서버와 연결되어 있음)
- 메인 페이지에 필요한 부분들만 몰아서 넣고 테스트 해본 영상입니다.
__상단이 기존 입력창, 하단이 비율 조정된 입력창입니다__
https://github.com/user-attachments/assets/68a9d199-e8aa-4341-9a62-3ff049e85569
- 아직 머지되지 않은 PR들과 충돌 가능성이 있어서 나중에 머지되는 PR만 주의하면 될 것 같습니다!

[수정 및 기능] iOS 모바일에서 input, textarea 확대되는 문제 해결

---

src/features/course-form/elements/contents.tsx

- 코스와 플랜 생성 시도 시 발생하는 에러를 해결했습니다.
- ✨ 오류 원인: `react-hook-form`의 `register`와 컴포넌트 내에서 직접 선언한 ref의 충돌
- ✨ 두 ref 모두 연결하여 해결
- closes #293 
테스트 성공 영상
https://github.com/user-attachments/assets/aa07d94b-b4d3-4dd8-a443-8998d59e5000
-

[긴급] 코스, 플랜 생성 오류 해결

---

src/features/place-review/image-view.tsx
src/views/detail-course/index.tsx

- 코스 상세 페이지, 장소 리뷰에서 기본 프로필 이미지 깨짐 문제 해결을 위한 PR
- ✨ 이미지 경로 수정
|기존|변경 후|
|---|---|
|![](https://github.com/user-attachments/assets/2bb781b8-627d-4401-a757-b48a9b8646ca)|![](https://github.com/user-attachments/assets/60f9175d-6c95-4e62-96c8-ff2b3f1e43cf)|

[HOTFIX] 기본 프로필 이미지 깨짐 문제 해결
