src/app/(legal)/privacy/page.tsx, src/app/(legal)/terms/page.tsx, src/app/components/SectionDivider.tsx, src/app/courses/new/page.tsx, src/app/getData.ts, src/app/page.tsx, src/types/Categories.ts
- 메인페이지 UI 구현
- ✨ 메인페이지 UI 구현
TODO:
- 코스 검색 API 연동
- 서비스 소개 이미지 만들기
=> [기능] 메인페이지UI 추가

package-lock.json, package.json, src/app/components/HamburgerMenu.tsx, src/app/components/Header.tsx, src/app/components/Menu.tsx, src/app/globals.css, src/app/layout.tsx, src/app/users/[id]/components/PlaceComponent.tsx, src/app/users/[id]/like/page.tsx
- 헤더의 메뉴바 구현
- ✨ Hamburger 아이콘 수정
- ✨ 메뉴바 UI 구현
|모바일|pc|
|---|---|
|![](https://github.com/user-attachments/assets/26527dd5-1ac3-483f-9081-c562f402e4f7)|![](https://github.com/user-attachments/assets/1a83e450-bcf4-44eb-8793-5f7ba08f86cb)|
- 메뉴 리스트 중 `내가 작성한 댓글`, `진행 중인 이벤트`, `공지사항`은 화면 설계된게 없어서 우선 내비게이션 경로는 `/`으로 설정했습니당
- 모바일뷰랑 pc랑 다른점은 햄버거 아이콘 이동하는거..!
=> [기능] 메뉴바 UI 구현

src/app/schedules/[id]/update/page.tsx, src/app/schedules/components/CourseCard.tsx
- 코스 플랜 수정 페이지 UI 구현
- ✨ UI 구현
- 이전 PR 머지되면 rebase해서 다시 올릴게여
-  화면설계 된거 없어서 생성 페이지랑 비슷하게 만들었슴다
- 나중에 DndContext도 컴포넌트로 빼도 좋을듯..?
=> [기능] 코스 플랜 수정 페이지 구현

package-lock.json, package.json, src/app/components/KakaoMap.tsx, src/app/courses/new/page.tsx, src/app/schedules/[id]/update/page.tsx, src/app/schedules/new/page.tsx, tsconfig.json
- 빌드 오류 해결을 위한 pr입니다.
- ✨ 카카오맵 타입 추가
- ✨ any 대신 타입 명시
- 개발할 때 최대한 any는 지양해주세욥
=> [수정] 빌드 오류 해결

src/app/components/Footer.tsx, src/app/components/LayoutSpacer.tsx, src/app/manifest.ts
- 이 PR은 manifest 추가 및 핸드폰 뷰에 맞는 스타일 수정을 위한 Pr입니다.
- ✨ manifest 추가
- ✨ 기타 스타일 수정
|manifest 적용|
|---|
|![IMG_024CF4F47AE9-1](https://github.com/user-attachments/assets/f1440b27-2ae4-49e3-9e6a-e4eb83c9e860)|
=> [기능] manifest 추가 및 기타 수정

src/app/components/(main)/BannerSection.tsx, src/app/components/(main)/BottomSection.tsx, src/app/components/(main)/EventItem.tsx, src/app/components/(main)/EventSection.tsx, src/app/components/(main)/LikeCourseItem.tsx, src/app/components/(main)/LikeCourseSection.tsx, src/app/components/(main)/NewCourseItem.tsx, src/app/components/(main)/NewCourseSection.tsx, src/app/components/(main)/NoticeItem.tsx, src/app/components/(main)/NoticeSection.tsx, src/app/components/Footer.tsx, src/app/layout.tsx, src/app/login/components/Login.tsx, src/app/login/components/Splash.tsx, src/app/login/page.tsx, src/app/page.tsx
- 이 PR은 classname 수정을 위한 pr입니다.
- ✨ classname 중괄호 삭제
=> [수정] classname 형식 수정

src/app/courses/[id]/getData.tsx, src/app/courses/[id]/page.tsx
- 이 PR은 코스 상세 디자인에 맞게 수정을 위한 pr입니다.
- ✨ 코스 상세 수정
- 디자인 완료되면 그에 맞게 추가 수정하겠습니답
=> [기능] 코스 상세 디자인에 맞게 수정

package-lock.json, package.json, src/app/layout.tsx, src/app/template.tsx
- 이 PR은 화면 전환 모션 추가를 위한 PR입니다.
- ✨ framer-motion 추가
- ✨ 화면 easeinout 추가
https://github.com/user-attachments/assets/76db3dd1-c2d8-435c-b956-b346725a53cc
티는 잘 안나지만 easeinout 추가해서 조금은 부드러워졌슴다
=> [기능] 화면 전환 모션 추가

src/app/components/(layout)/Header.tsx, src/app/components/(main)/EventSection.tsx, src/app/components/(main)/LikeCourseSection.tsx, src/app/components/(main)/NewCourseSection.tsx, src/app/components/(main)/NoticeSection.tsx, src/app/components/(main)/SearchComponent.tsx, src/app/login/components/Login.tsx, src/app/page.tsx
- 컴포넌트 경로 수정에 대한 PR입니다.
- ✨ layout 컴포넌트 경로 수정
=> [수정] 컴포넌트 경로 수정

src/app/components/FloatingWriteButton.tsx, src/app/courses/page.tsx, src/app/schedules/page.tsx
- 플로팅 작성 버튼을 추가하기 위한 PR입니다.
- ✨ 플로팅 버튼 컴포넌트 생성
- ✨ 플랜/생성 버튼에 적용
https://github.com/user-attachments/assets/160afc74-901c-4d29-ac5b-78c2377f8649
=> [기능] 플로팅 작성 버튼 추가

src/app/components/(layout)/Header.tsx, src/app/notifications/components/NotificationItem.tsx, src/app/notifications/page.tsx, src/app/notifications/types.ts
- 이 PR은 알림 페이지 뷰 추가를 위한 pr 입니다.
- ✨ 알림 목록 페이지 추가
- ✨ 알림 컴포넌트 추가
|알림 페이지|
|---|
|<img width="375" alt="image" src="https://github.com/user-attachments/assets/aa143211-fa83-42be-9dc8-9ba3885408df" />|
- 서버와 알림 관련해서 연동 필요
=> [기능] 알림 페이지 추가

src/app/components/(layout)/Footer.tsx, src/app/users/[id]/setting/page.tsx
- 이 PR은 유저 수정 UI 추가를 위한 pr입니다.
- ✨ footer 수정
- ✨ 유저 수정 UI 추가
|유저 수정|
|---|
|<img width="377" alt="image" src="https://github.com/user-attachments/assets/15d346ba-f910-4faa-991f-67c7667dc17c" />|
=> [기능] 유저 수정 UI 추가

package-lock.json, package.json, src/app/components/SortableItem.tsx, src/app/courses/[id]/components/CommentItem.tsx, src/app/layout.tsx, src/app/provider/ReactQueryProvider.tsx, src/app/users/[id]/components/ProfileTag.tsx
- 이 PR은 axios 및 react-query 적용을 위한 PR입니다.
- ✨ query provider 적용
- ✨ axios 설치
=> [기능] axios 및 react-query 적용

app/oauth/kakao/callback/page.tsx, app/plans/page.tsx, app/users/[id]/page.tsx, next.config.js, package-lock.json, package.json, src/entities/login/api.ts, src/entities/user/api.ts, src/entities/user/type.ts, src/features/user/upload-profile-image.tsx, src/shared/api/index.ts, src/shared/axios/index.ts, src/shared/utils/imageUtil.ts, src/views/detail-user/index.tsx, src/views/update-user/index.tsx, src/widgets/header/index.tsx
- 이 PR은 유저 정보 수정 기능 추가를 위한 PR입니다.
- ✨ 유저 정보 수정 로직 추가
- ✨ 이미지 업로드 로직 추가
- ✨ react-hook-form 추가
- react-hook-form 써서 게시글 업로드, 수정 등등 input 있는 곳들 천천히 바꿔봅시닷
=> [기능] 유저 정보 수정 기능 추가

app/users/[id]/wishlist/page.tsx, src/views/list-course/index.tsx, src/widgets/header/index.tsx, src/widgets/list-course/index.tsx
- 관심 목록 페이지 구현 PR
- ✨ 관심목록 페이지 추가
|리스트뷰|그리드뷰|
|---|---|
|![](https://github.com/user-attachments/assets/a321bb5f-1108-46f3-8dd3-b72876fe4742)|![](https://github.com/user-attachments/assets/1e7cd06e-89e0-4b2e-b774-e1bfca6e6a21)|
=> [기능] 관심목록 페이지 구현

app/layout.tsx, src/views/main/index.tsx, src/widgets/course-plan-layout/index.tsx, src/widgets/default-header/index.tsx, src/widgets/header/index.tsx
- 이 PR은 헤더 수정 및 메인 페이지 수정을 위한 PR입니다.
- ✨ 헤더 수정
- ✨ 코스,플랜 상세용 헤더 추가
- ✨ 메인 페이지 수정
https://github.com/user-attachments/assets/af5bf90e-7c47-4f9d-992c-20828c189230
=> [수정] 헤더 수정 및 메인 페이지 수정

app/courses/[id]/comments/page.tsx, app/courses/[id]/modify/page.tsx, app/courses/[id]/page.tsx, app/courses/page.tsx, app/plans/page.tsx, app/users/[id]/wishlist/page.tsx, src/entities/comment/api.ts, src/entities/course/api.ts, src/entities/login/api.ts, src/entities/user/type.ts, src/features/course/card-grid-course.tsx, src/features/course/form-course.tsx, src/features/course/grid-course.tsx, src/features/main/section-like-course.tsx, src/features/main/section-new-course.tsx, src/shared/ui/RegionCascader.tsx, src/shared/ui/SelectCategories.tsx, src/views/detail-comment/index.tsx, src/views/detail-course/index.tsx, src/views/list-course/index.tsx, src/views/search-course/index.tsx, src/views/search-place/index.tsx, src/views/update-course/index.tsx, src/widgets/course-plan-layout/index.tsx, src/widgets/header/index.tsx, src/widgets/list-course/index.tsx
- 이 PR은 코스 수정 추가 및 기타 수정을 위한 PR입니다.
- ✨ 코스 수정 페이지 추가
- ✨ 코스 생성 페이지 리팩토링
- ✨ 장소 추가 페이지 수정
- ✨ 코스 목록 페이지 api 연동
- ✨ 코스 api search params 추가
=> [기능] 코스 수정 추가 및 기타 수정

app/courses/[id]/comments/page.tsx, app/courses/[id]/modify/page.tsx, app/courses/[id]/page.tsx, app/layout.tsx, app/not-found/page.tsx, app/plans/page.tsx, package.json, src/entities/comment/query.ts, src/entities/course/query.ts, src/entities/login/api.ts, src/entities/user/query.ts, src/features/course/form-course.tsx, src/features/main/section-like-course.tsx, src/features/main/section-new-course.tsx, src/features/place/drag-place-item.tsx, src/shared/axios/index.ts, src/views/detail-comment/index.tsx, src/views/detail-course/index.tsx, src/views/detail-user/index.tsx, src/views/list-course/index.tsx, src/views/search-course/index.tsx, src/views/search-place/index.tsx, src/views/update-course/index.tsx, src/views/update-user/index.tsx, src/widgets/add-course-plan/index.tsx, src/widgets/default-footer/index.tsx, src/widgets/drag-place/index.tsx, src/widgets/header/index.tsx, src/widgets/list-course/index.tsx
- 이 PR은 react-query 도입 및 기타 수정을 위한 PR입니다.
- ✨ react-query 도입
- ✨ 기타 로직 수정
- 로딩중일 때 스켈레톤 ui 추후 추가 필요
=> [기능] react-query 도입 및 기타 수정

app/plans/page.tsx, src/entities/course/type.ts, src/entities/place/type.ts, src/entities/plan/api.ts, src/entities/plan/query.ts, src/entities/plan/type.ts, src/features/course/form-course.tsx, src/features/place/drag-place-item.tsx, src/features/plan/blank-tooltip.tsx, src/features/plan/card-plan.tsx, src/shared/ui/KakaoMap.tsx, src/shared/ui/PlaceCollapse.tsx, src/views/list-plan/index.tsx, src/views/search-place/index.tsx, src/views/update-course/index.tsx, src/widgets/add-course-plan/index.tsx, src/widgets/drag-place/index.tsx
- 플랜 목록 페이지 구현을 위한 PR
- ✨ 플랜 목록 페이지 UI 구현
- ✨ 플랜 없는 유저 페이지 UI 구현
- ✨ 미로그인 페이지 UI 구현
- ✨ CardCourse 마우스 호버 스타일 변경 이벤트 추가
|플랜 목록|플랜 없는 유저|미로그인|
|---|---|---|
|![image](https://github.com/user-attachments/assets/92ae142e-2ebc-417a-b58a-e09cd4b377cb)|![image](https://github.com/user-attachments/assets/d45bbe66-a3fa-47b9-a625-64d905d5c481)|![](https://github.com/user-attachments/assets/9c7b52a6-5966-4fa5-bd14-5dcf07baebd3)
=> [기능] 플랜 목록 페이지 구현

app/courses/[id]/update/page.tsx, app/plans/[id]/page.tsx, src/entities/plan/api.ts, src/entities/plan/query.ts, src/entities/plan/type.ts, src/views/detail-plan/index.tsx, src/widgets/course-plan-layout/index.tsx, src/widgets/floating-write-btn/index.tsx
- 플랜 상세 조회 페이지 UI 구현 및 api 연결을 위한 PR
- ✨ UI 구현 및 api 연결
- ✨ 플로팅 버튼 수정
https://github.com/user-attachments/assets/f44e3998-e7f4-4041-afd3-8a4c21358579
- 코스로 공유할 때 정보 넘겨주는 로직 구현 필요
- 플랜 생성, 수정 페이지 진행중
=> [기능] 플랜 상세 조회 페이지 UI 구현 및 api 연결

src/entities/plan/api.ts, src/entities/plan/query.ts, src/entities/plan/type.ts, src/features/course/form-course.tsx, src/views/search-place/index.tsx, src/widgets/add-course-plan/index.tsx
- 플랜 생성 페이지 UI 구현 및 api 연결을 위한 PR
- ✨ UI 구현 및 api 연결
https://github.com/user-attachments/assets/f6bb5776-3464-4be9-a202-de0449dc9196
=> [기능] 플랜 생성 페이지 UI 구현 및 api 연결

app/layout.tsx, app/plans/[id]/update/page.tsx, app/template.tsx, app/users/[id]/page.tsx, src/entities/course/api.ts, src/entities/course/query.ts, src/features/course/card-list-course.tsx, src/features/main/section-announcement.tsx, src/features/main/section-like-course.tsx, src/features/place/drag-place-item.tsx, src/features/plan/list-user-place.tsx, src/features/user/user-profile-section.tsx, src/features/user/user-tab-button.tsx, src/views/detail-user/index.tsx, src/views/search-course/index.tsx, src/views/update-plan/index.tsx, src/views/update-user/index.tsx, src/widgets/course-plan-detail-layout/index.tsx, src/widgets/course-plan-form-layout/index.tsx
- 이 PR의 목적은 UI 수정 및 로직 수정을 위한 PR입니다.
- ✨ figma ui 반영
- ✨ 불필요한 import 문 제거
- ✨ 로그아웃 및 유저 프로필 변경 시 queryClient 수정
=> [수정] UI 수정 및 로직 수정

src/entities/course/api.ts, src/entities/course/query.ts
=> [수정] 빌드 오류 수정

app/courses/by-region/page.tsx, app/users/[id]/wishlist/page.tsx, src/entities/course/query.ts, src/features/user/user-profile-section.tsx, src/features/user/user-tag.tsx, src/views/list-course/index.tsx, src/widgets/course-list-layout/index.tsx, src/widgets/header/index.tsx
- 관심 코스 목록 페이지 UI 구현을 위한 PR
- ✨ 코스 목록 layout 생성
- ✨ 관심 코스 목록 페이지 UI 구현
https://github.com/user-attachments/assets/42a26c79-065e-4ee2-b5c7-da8c2b0292da
- [제일 마지막 커밋](https://github.com/team-joytas/wooco-fe/commit/bc42a1c5c768f6bf1d7e63f7588e6863197ad1c6)만 보면 이 pr 변경사항 볼 수 있습니답
- 이전 pr에서 올렸던 코드 수정한 부분도 있어서 그냥 같이 올려용
=> [기능] 관심 코스 목록 페이지 UI 구현

package-lock.json, package.json, src/shared/axios/index.ts, src/shared/axios/signature.ts, src/shared/ui/RegionCascader.tsx, src/views/list-course/index.tsx, src/widgets/default-footer/index.tsx
- 이 PR은 토큰 reissue 로직 추가을 위한 PR 입니다.
- ✨ 빌드 오류 수정 (훅 룰 위반)
- ✨ 토큰 reissue 로직 추가
- ✨ 불필요한 쿼리 호출 제거
=> [기능] 토큰 reissue 로직 추가

src/shared/ui/PlaceCollapse.tsx
- 이 PR은 장소 order 적용을 위한 PR입니다.
- ✨ order 순으로 정렬
=> [수정] 장소 order 적용

src/widgets/course-plan-form-layout/index.tsx, src/widgets/header/index.tsx
- 코스/플랜 수정 페이지 관련 오류 해결을 위한 PR
- ✨ 조건문 수정
=> [수정] 코스/플랜 수정 페이지 오류 해결

src/features/course/list-user-course.tsx, src/views/detail-user/index.tsx
- 이 PR은 유저 코스 없을 시 ui 추가를 위한 PR입니다.
- ✨ 유저의 코스가 없을 시 안내 문구 추가
=> [수정] 유저 코스 없을 시 ui 추가

src/entities/comment/api.ts, src/entities/comment/query.ts, src/entities/comment/type.ts, src/features/comment/card-comment.tsx, src/views/detail-comment/index.tsx, src/views/detail-course/index.tsx
- 이 PR의 목적은 댓글 삭제 api 연결을 위한 PR입니다.
- ✨ api 연결
- ✨ 댓글 삭제 로직 추가
=> [수정] 댓글 삭제 api 연결

.github/workflows/CODEOWNERS
- 리뷰어 설정을 위한 워크플로우 생성 PR
- ✨ CODEOWNERS 파일 추가
=> [설정] 리뷰어 설정 추가

src/features/course/form-course.tsx
- 플랜의 카테고리 항목 삭제를 위한 PR
- ✨ 플랜 생성 페이지에서 카테고리 설정 항목 삭제
=> [수정] 플랜의 카테고리 항목 삭제

src/features/course/form-course.tsx, src/shared/ui/SelectCategories.tsx
- 카테고리 2개 이상 설정 시 오류 수정을 위한 PR
- ✨ 카테고리 설정 기능 수정
- 본 PR만의 수정사항은 [fix: 카테고리 설정 오류 수정](https://github.com/team-joytas/wooco-fe/commit/6e608dd802c9892f4cce61c3fc536e2854e2fa3f) 여기서 확인해주세용
=> [수정] 카테고리 설정 기능 수정

src/features/course/form-course.tsx, src/views/list-course/index.tsx, src/views/main-course/index.tsx
- 지난 25/02/02 내부 QA에서 발견한 제안 사항들에 관한 구현
- 장소 검색 중에도 새 코스 작성 가능
- 장소 검색 후 코스 또는 플랜 작성시 자동 기입
- 코스 또는 플랜 페이지 타입에 따라 날짜 선택 최대, 최소값 제한
- #98 
- #99
=> [기능 및 수정] DatePicker max/min 제한, 임의 지역을 선택한 코스 목록에서 플로팅 버튼 미등장

src/features/course/form-course.tsx, src/shared/ui/KakaoMap.tsx, src/widgets/course-plan-detail-layout/index.tsx, src/widgets/course-plan-form-layout/index.tsx, src/widgets/drag-place/index.tsx
- 관련 이슈 버그 해결
- Kakao map 동적 생성 로직 변경으로 중복 호출 방지
- place 배열의 변화를 감지하면 marker 전체를 삭제 후 재 생성
- #126
=> [수정] 플랜-코스 edit 중 장소 순서 변경 로직 수정

src/shared/ui/KakaoMap.tsx
- any 타입을 허용하지 않는 Eslint 규칙 적용
=> hotfix: 빌드 에러 해결

src/shared/ui/ImageWithIndex.tsx
- 인덱스 있는 이미지 스타일 변경을 위한 PR
- ✨ 이미지 스타일 변경
#100 
|변경전|변경후|
|---|---|
|![](https://github.com/user-attachments/assets/ff1529f6-7967-4793-a5ee-6a2d6c8f0472)|![](https://github.com/user-attachments/assets/dd03a3da-1374-4243-83e5-008bf872dc1b)|
=> [디자인] 인덱스 표시 이미지 스타일 수정

src/features/course/form-course.tsx, src/shared/ui/HelperText.tsx
- helper text 스타일 수정을 위한 PR
- ✨ helper text 컴포넌트 추가 및 적용
- closes #101 
|변경전|변경후|
|---|---|
|![](https://github.com/user-attachments/assets/c3104163-8365-4b29-a66d-dfd03531d68a)|![](https://github.com/user-attachments/assets/6162ad3d-26f7-4443-acfe-f577bf981af3)|
- 저장하면서 prettier도 자동 적용된 것 같습니다. 하이든 아직 prettier 적용이 안된 것 같아요 확인 부탁드려요오
=> [기능] HelperText 컴포넌트 추가

src/widgets/floating-write-btn/index.tsx
- FloatingWriteButton 관련 빌드 에러 해결을 위한 PR
- ✨ FloatingWriteButton의 props 조건 설정
=> [빌드] 빌드 에러 해결

next.config.js
- 이미지 허용 도메인 추가
- ✨ next.config.ts에 구글 이미지 도메인 추가
=> [빌드] 이미지 허용 도메인 추가

app/layout.tsx, src/widgets/default-footer/index.tsx
- 레이아웃 폰트를 설정하고 푸터 디자인을 수정한 PR입니다.
- ✨ 레이아웃 폰트를 body 태그에 추가했습니다.
- ✨ 푸터 디자인을 수정했습니다.
|변경전|변경후|
|---|---|
|![](https://github.com/user-attachments/assets/bc356c3e-a0da-450d-8608-4ab876f436eb)|![](https://github.com/user-attachments/assets/b4cef220-e53d-4ca9-bd8b-776fd680820c)|
=> [디자인] 폰트 설정 및 푸터 디자인 수정

src/entities/place/type.ts, src/features/course/form-course.tsx, src/shared/ui/KakaoMap.tsx, src/widgets/course-plan-detail-layout/index.tsx, tailwind.config.ts
- 카카오맵 컴포넌트를 2종류로 분류하는 PR
- ✨ ActiveKakaoMap: 코스, 플랜 페이지 / 지역 변경 및 마커 생성
- ✨ KakaoMap: 장소 리뷰 페이지 / 장소에 대한 마커만 1개
- ✨ 코스/플랜 상세 페이지의 세부 디자인 수정
=> [수정] 카카오맵 컴포넌트 추가

app/places/[id]/reviews/page.tsx, src/entities/place/api.ts, src/entities/place/query.ts, src/features/place/card-review.tsx, src/shared/ui/OptionDropbox.tsx, src/views/detail-place/index.tsx, src/views/list-place-review/index.tsx, src/widgets/default-header/index.tsx, src/widgets/header/index.tsx
- 장소 리뷰 목록 페이지 구현을 위한 PR
- ✨ 장소 리뷰 목록 페이지 구현
- ✨ 리뷰 삭제 api 연결
- ✨ 세부 디자인 수정
closes #111 
- 피그마 코멘트 논의
=> [기능] 장소 리뷰 목록 페이지 구현

src/features/main/section-announcement.tsx, src/features/main/section-banner.tsx, src/features/main/section-bottom.tsx, src/features/main/section-like-course.tsx, src/features/main/section-new-course.tsx, src/features/plan/blank-tooltip.tsx, src/shared/ui/ProfileImage.tsx, src/views/detail-comment/index.tsx, src/views/list-plan/index.tsx, src/views/update-user/index.tsx, src/widgets/course-plan-detail-layout/index.tsx, src/widgets/default-header/index.tsx, src/widgets/floating-write-btn/index.tsx
- 세부 디자인과 버그를 수정한 PR
- ✨ 원본 이미지 렌더링을 위한 이미지 커스텀 로더 추가
- ✨ 마우스 hover 이벤트 및 세부 디자인 수정
- ✨ 메인 페이지 레이아웃 및 디자인 수정
closes #114, #115, #125, #141, #147 
|변경전|변경후|
|---|---|
|![image](https://github.com/user-attachments/assets/8074f561-57df-49b8-9df4-1ab4d0fda474)|![image](https://github.com/user-attachments/assets/7cdc404c-9f2d-429e-9830-6ce31d3fb547)|
- 커밋별로 코드 수정사항 보는게 편하실 것 같습니당
=> [디자인 및 기능] 세부 디자인 및 이미지 커스텀 로더 추가

src/entities/place/api.ts, src/entities/place/type.ts, src/entities/plan/type.ts, src/features/main/section-like-course.tsx, src/shared/ui/PlaceCollapse.tsx, src/views/detail-place/index.tsx, src/views/search-place/index.tsx, src/widgets/course-plan-form-layout/index.tsx
- API 수정에 따른 프론트엔드 코드 수정
- ✨ 플랜 > categories 정보 제거
- ✨ kakao_map_place_id -> kakao_place_id
=> [수정] API 수정사항 적용

src/widgets/default-header/index.tsx
- default-header가 표시되는 페이지 수정을 위한 PR
- ✨ header가 표시되는 페이지 url을 변수로 정의하여 조건문 설정
=> [수정] 헤더 표시 위치 수정

app/users/[id]/page.tsx, src/entities/course/api.ts, src/entities/course/query.ts, src/features/main/section-new-course.tsx, src/views/detail-user/index.tsx, src/views/list-course/index.tsx, src/views/list-like-course/index.tsx, src/views/main-course/index.tsx, src/views/search-course/index.tsx, src/widgets/header/index.tsx
- 마이페이지 코스 목록 조회 관련 오류 수정
- ✨ 마이페이지에 필요한 유저 정보 조회 위치를 detail-user로 수정
- ✨ 코스 목록 정렬 기준 설정에 대한 오류 수정 (소문자 -> 대문자, order -> sort)
=> [수정] 마이페이지 코스 목록 정렬 오류 수정

src/features/index.ts, src/features/place-collapse/index.ts, src/features/place-collapse/place-collapse.tsx, src/widgets/course-plan-detail-layout/index.tsx
- 장소 collapse 디자인 수정을 위한 PR
- ✨ Collapse의 레이아웃과 디자인 수정
- closes #137 
|변경전|변경후|
|---|---|
|![image](https://github.com/user-attachments/assets/d18806c1-6679-4eff-9452-9c5e6277503f)|![image](https://github.com/user-attachments/assets/94296e4b-1e5c-4a0f-99a0-940849f29969)|
- 이 PR도 마지막 커밋만 봐주십셔 ...
=> [수정] 장소 Collapse 디자인 수정

src/features/place/form-review.tsx
- 타입이 지정되지 않은 버튼이 submit 속성으로 자동 배정되어 의도치 않게 form을 제출하는 현상
- ✨ button type 지정
- 예: #195
=> [수정-장소 리뷰 작성] 이미지 업로드 시도 시 페이지 나가짐 현상 수정

src/widgets/default-header/index.tsx
- 기본 헤더 스크롤 관계 없이 상단에 고정
- ✨ DefaultHeader component fixed, z-index style 부여
- ✨ Component 자체 Margin 부여를 위해 Spacer 추가
- #166
=> [기능] 헤더 상단 고정

src/features/place/form-review.tsx, src/views/search-place/index.tsx
- ✨ 불필요한 Ant design 컴포넌트 제거 및 직접 구현
- ✨ IME 입력기 관련 버그 수정, 키보드 이벤트의 isComposing 속성 활용
- closes #174  
- closes #168
=> [기능] 장소 검색 결과 목록 디자인 적용

app/oauth/[provider]/callback/page.tsx
- 디버깅을 위해 작성된 불필요한 로그 삭제
- #209  
- #210
=> chore: 불필요 로그 삭제

src/shared/ui/ProfileImage.tsx
- hydration error 해결
- ✨ ProfileImage에 LegacyBehavior 옵션 추가
=> [수정] Hydration Error 해결을 위해 ProfileImage에 LegacyBehavior 옵션 추가

src/views/detail-place/index.tsx, src/views/detail-place/section.tsx
- 장소 상세 페이지에서 리뷰 없을 경우에 대한 화면을 구현
- ✨ 리뷰 없는 경우 표시
- ✨ /detail-place/index.ts 리팩토링
- closes #183
=> [기능] 장소 상세 리뷰 없는 화면 구성

src/views/detail-place/index.tsx
- 장소 상세 페이지의 리뷰 정보를 확인하는 조건문을 수정했습니다.
- ✨ reviewData의 길이를 정확히 판별하지 못하는 것 같아 placeData의 review_count로 판별하도록 수정
=> [수정] 장소 상세 페이지의 리뷰 길이 판단 조건문 수정

src/entities/comment/api/delete-comment.ts, src/entities/comment/api/update-comment.ts, src/entities/course/api/delete-course.ts, src/entities/course/api/get-courses.ts, src/entities/course/api/post-course.ts, src/entities/course/api/queryKey.ts, src/entities/notification/api/read-notification.ts, src/entities/place/api/delete-place-review.ts, src/entities/place/api/post-place-review.ts, src/entities/place/api/update-place-review.ts, src/entities/user/api/delete-my-region-preferences.ts, src/entities/user/api/post-my-regions-preferences.ts, src/features/notification/card-notification.tsx, src/widgets/course-plan-form-layout/index.tsx, src/widgets/header/index.tsx, src/widgets/review-comment-card/index.tsx
- queryKey 오류 수정 및 코스 목록 조회 오류 수정
- ✨ React Query의 QueryKey 수정
- ✨ 코스 목록 조회 훅의 gcTime 설정
-
https://github.com/user-attachments/assets/748c4b91-225e-4035-86f7-8b64bd6eaf60
-
=> [수정] queryKey 관련 빌드 에러 수정 및 코스 목록 조회 시 변경된 좋아요 반영

src/features/select-sort/index.ts, src/features/select-sort/option.tsx, src/features/select-sort/options.ts, src/features/select-sort/select-sort.tsx, src/views/detail-user/index.tsx, src/views/list-course/index.tsx, src/views/list-like-course/index.tsx
- 정렬 기준 설정을 위한 드롭다운의 디자인을 반영하고, 위치를 수정했습니다.
- ✨ antd의 Select 컴포넌트를 활용하던 구조를 직접 구현으로 대체
- closes #248 
https://github.com/user-attachments/assets/20d4c94a-6658-4757-9725-49f27d5279ef
-
=> [디자인] 정렬 드롭다운 디자인 반영 및 위치 수정 (#248)

src/widgets/header/main-header.tsx
다음 4가지 path에서만 header 표기
- /
- /courses
- /plans
- /not-found
- closes #240
=> [기능] 일부 페이지에 Header 미표시

src/features/course-card/grid-card/grid-card.tsx
- Fix #264
- ✨ Placeholder 이미지 설정
-  closes #264
=> [수정-코스 카드] 이미지 비정상일 경우 레이아웃이 깨지는 문제

src/views/search-place/index.tsx
=> [기능] 장소 검색/추가 페이지 세부 디자인 변경

src/shared/ui/region-cascader.tsx
- #146 해소
- ✨ antd 종속성 제거
- resolves #146
---
=> [수정-코스 목록] 지역 Cascader 스타일 수정
